#index:
#    path: /
#    controller: App\Controller\DefaultController::index

author-login-check:
    path: /author-login-check

admin-login-check:
    path: /admin-login-check

logout:
    path: /logout


